name: Build JAR

on:
  push:
    branches:
      - main  # or the branch you want to trigger the build
  pull_request:
    branches:
      - main  # or the branch you want to trigger the build
  schedule:
      - cron: '0 23 * * *'  # Runs at midnight UTC+1 (23:00 UTC)

jobs:
  build:
    name: Build and Package Mod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt-openjdk'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mod-jar
          path: build/libs/*.jar
